# Generated by Django 2.1.5 on 2019-01-09 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool_ladder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='played',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
