# Generated by Django 2.1.5 on 2019-01-09 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool_ladder', '0002_match_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
