# Generated by Django 2.1.5 on 2019-01-15 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pool_ladder', '0003_game_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['match', 'index']},
        ),
        migrations.RenameField(
            model_name='match',
            old_name='loser_position',
            new_name='challenger_position',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='winner_position',
            new_name='opponent_position',
        ),
        migrations.AlterField(
            model_name='match',
            name='challenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenger_match', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='match',
            name='opponent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opponent_match', to=settings.AUTH_USER_MODEL),
        ),
    ]
