# Generated by Django 2.1.5 on 2019-01-15 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pool_ladder', '0005_auto_20190115_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='start_rank',
        ),
    ]
