# Generated by Django 2.1.5 on 2019-01-15 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pool_ladder', '0006_remove_userprofile_start_rank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['rank']},
        ),
    ]
