# Generated by Django 2.1.5 on 2019-01-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool_ladder', '0008_auto_20190115_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='slack_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
