# Generated by Django 2.1.5 on 2019-01-18 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pool_ladder', '0009_userprofile_slack_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='slack_name',
            new_name='slack_id',
        ),
    ]
