# Generated by Django 2.1.5 on 2019-01-22 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pool_ladder', '0011_auto_20190120_2242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['challenge_time'], 'verbose_name_plural': 'matches'},
        ),
    ]
