# Generated by Django 2.1.5 on 2019-05-26 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool_ladder', '0012_auto_20190122_1634'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-challenge_time'], 'verbose_name_plural': 'matches'},
        ),
        migrations.AddField(
            model_name='match',
            name='days_to_play',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
