# Generated by Django 2.1.5 on 2019-05-27 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool_ladder', '0013_auto_20190526_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
