# Generated by Django 2.1.5 on 2019-05-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool_ladder', '0013_auto_20190416_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='declined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
