# Generated by Django 2.1.5 on 2019-05-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool_ladder', '0014_auto_20190514_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='days_to_play',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
