# Generated by Django 2.1.5 on 2019-05-27 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool_ladder', '0014_match_notified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='notified',
            new_name='declined',
        ),
        migrations.AddField(
            model_name='match',
            name='pending',
            field=models.BooleanField(default=False),
        ),
    ]
