# Generated by Django 2.2.1 on 2019-05-30 12:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pool_ladder', '0015_auto_20190527_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_started', models.DateTimeField(default=django.utils.timezone.now)),
                ('number', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['-date_started'],
            },
        ),
        migrations.AlterField(
            model_name='match',
            name='challenge_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='match',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pool_ladder.Season'),
        ),
    ]
